version: "3"

services:
  db:
    image: "mysql"
    container_name: sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tattleviralspiral
      MYSQL_ROOT_PASSWORD: "helloworld"
    volumes:
      - "~/data/viral-spiral/db:/var/lib/postgresql/data/"

  db_gui:
    image: adminer
    container_name: db_gui
    restart: always
    ports:
      - 8080:8080
